#ifndef P2PD_VERSION_H
#define P2PD_VERSION_H

#define P2PD_VERSION "0.1.0"
#define P2PD_VERSION_MAJOR 0
#define P2PD_VERSION_MINOR 1
#define P2PD_VERSION_PATCH 0
#define P2PD_VERSION_NUMBER \
    ((P2PD_VERSION_MAJOR << 16) | (P2PD_VERSION_MINOR << 8) | P2PD_VERSION_PATCH)

#endif // P2PD_VERSION_H